# Generated by Django 5.2.5 on 2026-04-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plaza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador", models.CharField(max_length=15, unique=True)),
                ("ocupada", models.BooleanField(default=False)),
                ("patente", models.CharField(blank=True, max_length=10, null=True)),
                ("hora_ingreso", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
