# Generated by Django 5.2.5 on 2026-04-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistroCobro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identificador_plaza", models.CharField(max_length=20)),
                ("patente", models.CharField(max_length=10)),
                ("hora_ingreso", models.DateTimeField()),
                ("hora_salida", models.DateTimeField(auto_now_add=True)),
                ("minutos", models.IntegerField()),
                ("total_pagado", models.IntegerField()),
            ],
        ),
    ]
