services:
  - type: web
    name: danny-park
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn parking_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
